# Generated by Django 5.0.3 on 2024-03-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_cliente_delete_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150)),
                ('Barrio', models.CharField(max_length=120)),
                ('Localidad', models.CharField(max_length=120)),
                ('Fecha_de_compra', models.DateField()),
                ('Nombre_Producto', models.CharField(max_length=120)),
                ('Valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
