# Generated by Django 5.0.3 on 2024-03-20 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_client_delete_cliente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Cliente',
        ),
    ]
